### ISSUE TITLE
Enemy movement becomes faster with increase in frame speed 

### ISSUE THREAD

**Issue by parth-p** [kushagra189/bomberman#2]
When W,A,S,D is pressed for a long time continuously, then frame speed increases and so does the enemy speed.

- [x] Bug report

- [ ] Question

- [ ] Feature request

**Comment by vivek-7** [comment]
@parth-p  I would not like to work on this issue.

- [x] Please Do this yourself @kushagra189 

- [x]  This assignment is copied

- [x] Jai Mata Di

**Comment by parth-p** [comment]
Sure don't go ahead.
